version: '3'

services:
  project-pets-dev:
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - "./src:/app/src"
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: yarn start:dev
    restart: always
